
import '../globals.css'
import { Inter } from 'next/font/google'
import TodoList from './todoList'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="flex gap-y-1">
      <TodoList />
        {children}
      </main>
        </body>
    </html>
  )
}
