import Header from './Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: "Lucky's Pages",
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          Lucky own page
          </title>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        </body>
    </html>
  )
}
